### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by aubreywullschleger** [txr243/prj-rev-bwfs-dasmoto#5]
Grade: Meets Expectations

Summary:
Awesome job on your project! I love the organization of your HTML and how easy your code is to read.  I also appreciate the lack of repetitive code in your CSS. Keep it up!

One thing to work on would be to make sure that the syntax of your HTML is correct, specifically wrapping all of your id values in quotes.

Next, I will challenge you to make your site mobile friendly by researching and implementing responsive design techniques like media queries (see here: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries and here: https://css-tricks.com/snippets/css/media-queries-for-standard-devices/ ). I think you are ready for this challenge based on your work here. Great job!

**Comment by txr243** [comment]
Thank you!
